import { FooterUser } from "@/components/reusable/footer-user";
import { Header } from "@/components/reusable/header";
import { SidebarComponents } from "@/components/reusable/sidebar";
import { SidebarProvider } from "@/components/ui/sidebar";
import { Toaster } from "@/components/ui/toaster";
import type { Metadata } from "next";
import { cookies } from "next/headers";

import { ThemeProvider } from "@/lib/next-theme";
import { Poppins } from "next/font/google";
import { Suspense } from "react";
import "./globals.css";
import Loading from "./loading";
const poppins = Poppins({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700", "800", "300"],
});

export const metadata: Metadata = {
  title: "Stocks-Curency-System",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const cookieStore = await cookies();
  const defaultOpen = cookieStore.get("sidebar:state")?.value === "true";
  return (
    <html lang="en" suppressHydrationWarning={true}>
      <body className={` ${poppins.className} `}>
        <ThemeProvider
          attribute="class"
          defaultTheme="light"
          enableSystem={true}
          disableTransitionOnChange
        >
          <SidebarProvider defaultOpen={defaultOpen}>
            <SidebarComponents />
            <main className="w-full min-h-full h-full">
              <Suspense fallback={<Loading />}>
                <Header />
                {children}
              </Suspense>
            </main>
            <Toaster />
            <FooterUser />
          </SidebarProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
